from selenium.webdriver.common.by import By

order_header = [By.CLASS_NAME, "Order_Header__BZXOb"]
firstname_input = [By.XPATH, ".//input[@placeholder='* Имя']"]
lastname_input = [By.XPATH, ".//input[@placeholder='* Фамилия']"]
address_input = [By.XPATH, ".//input[@placeholder='* Адрес: куда привезти заказ']"]
metro_station_input = [By.XPATH, ".//input[@placeholder='* Станция метро']"]
metro_station_value = [By.XPATH, ".//div[@class='select-search__select']/ul/li[1]"]
phone_input = [By.XPATH, ".//input[@placeholder='* Телефон: на него позвонит курьер']"]
next_button = [By.XPATH, ".//div[@class='Order_NextButton__1_rCA']/button[text()='Далее']"]
date_input = [By.XPATH, ".//input[@placeholder='* Когда привезти самокат']"]
date_selected = [By.CLASS_NAME, 'react-datepicker__day--selected']
time_interval_block = [By.CLASS_NAME, "Dropdown-control"]
time_interval_list = [By.CLASS_NAME, "Dropdown-menu"]
one_day_interval = [By.XPATH, ".//div[@class='Dropdown-menu']/div[@class='Dropdown-option'][1]"]
five_day_interval = [By.XPATH, ".//div[@class='Dropdown-menu']/div[@class='Dropdown-option'][5]"]
black_color_checkbox = [By.ID, "black"]
grey_color_checkbox = [By.ID, "grey"]
comment_input = [By.XPATH, ".//input[@placeholder='Комментарий для курьера']"]
complete_order_button = [By.XPATH, ".//div[@class='Order_Buttons__1xGrp']/button[text()='Заказать']"]
order_modal = [By.CLASS_NAME, "Order_Modal__YZ-d3"]
agree_button = [By.XPATH, ".//div[@class='Order_Buttons__1xGrp']/button[text()='Да']"]
order_modal_header = [By.CLASS_NAME, "Order_ModalHeader__3FDaJ"]
check_status_button = [By.XPATH, ".//div[@class='Order_NextButton__1_rCA']/button[text()='Посмотреть статус']"]
